### ISSUE TITLE
Indeed.com not loading page specs ...it was working, then suddenly stopped.  No changes were made other than adding more words to filter out.

### ISSUE THREAD

**Issue by dckkendell** [EvAvKein/FilterJobsFeeds#1]
![Capture](https://github.com/user-attachments/assets/6a635067-730d-4e50-8ec5-d390915f644a)

**Comment by EvAvKein** [comment]
Indeed.com changed their website code, I updated the extension with a fix! The new version (1.11.1) is now uploaded to the Firefox and Chrome extension stores.

36d840338e6afc7d9674fa60f9a31a1f3a374de0
